export {default as Banner} from "./Banner"
export { default as Footer } from "./Footer"
export { default as Layout } from "./Layout"
export { default as Navbar } from "./Navbar"
export {default as Newsletter} from "./Newsletter"
export {default as Recomended} from "./Recomended"
export {default as Startpage} from "./Startpage"
export {default as Services} from "./Services"